//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Quic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuicWithDatagram.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed because the remote party sent a TLS alert: &apos;{0}&apos;..
        /// </summary>
        internal static string net_auth_tls_alert {
            get {
                return ResourceManager.GetString("net_auth_tls_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AddressFamily {0} is not valid for the {1} end point, use {2} instead..
        /// </summary>
        internal static string net_InvalidAddressFamily {
            get {
                return ResourceManager.GetString("net_InvalidAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied {0} is an invalid size for the {1} end point..
        /// </summary>
        internal static string net_InvalidSocketAddressSize {
            get {
                return ResourceManager.GetString("net_InvalidSocketAddressSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method may not be called when another {0} operation is pending..
        /// </summary>
        internal static string net_io_invalidnestedcall {
            get {
                return ResourceManager.GetString("net_io_invalidnestedcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuicConnection is configured to not accept any streams..
        /// </summary>
        internal static string net_quic_accept_not_allowed {
            get {
                return ResourceManager.GetString("net_quic_accept_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application layer protocol negotiation error was encountered..
        /// </summary>
        internal static string net_quic_alpn_neg_error {
            get {
                return ResourceManager.GetString("net_quic_alpn_neg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed: {0}..
        /// </summary>
        internal static string net_quic_auth {
            get {
                return ResourceManager.GetString("net_quic_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User configured callback failed..
        /// </summary>
        internal static string net_quic_callback_error {
            get {
                return ResourceManager.GetString("net_quic_callback_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote certificate is invalid because of errors in the certificate chain: {0}.
        /// </summary>
        internal static string net_quic_cert_chain_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_chain_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote certificate was rejected by the provided RemoteCertificateValidationCallback..
        /// </summary>
        internal static string net_quic_cert_custom_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_custom_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection timed out from inactivity..
        /// </summary>
        internal static string net_quic_connection_idle {
            get {
                return ResourceManager.GetString("net_quic_connection_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server refused the connection..
        /// </summary>
        internal static string net_quic_connection_refused {
            get {
                return ResourceManager.GetString("net_quic_connection_refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_connectionaborted {
            get {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CipherSuitePolicy must specify at least one cipher supported by QUIC..
        /// </summary>
        internal static string net_quic_empty_cipher_suite {
            get {
                return ResourceManager.GetString("net_quic_empty_cipher_suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection handshake was canceled due to the configured timeout of {0} seconds elapsing..
        /// </summary>
        internal static string net_quic_handshake_timeout {
            get {
                return ResourceManager.GetString("net_quic_handshake_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;&apos; should be within [0, {1}) range..
        /// </summary>
        internal static string net_quic_in_range {
            get {
                return ResourceManager.GetString("net_quic_in_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred. {0}.
        /// </summary>
        internal static string net_quic_internal_error {
            get {
                return ResourceManager.GetString("net_quic_internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be specified to accept the connection..
        /// </summary>
        internal static string net_quic_not_null_accept_connection {
            get {
                return ResourceManager.GetString("net_quic_not_null_accept_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server must provide a certificate in &apos;{0}&apos; or &apos;{1}&apos; or via &apos;{2}&apos; for the connection..
        /// </summary>
        internal static string net_quic_not_null_ceritifcate {
            get {
                return ResourceManager.GetString("net_quic_not_null_ceritifcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be specified to start the listener..
        /// </summary>
        internal static string net_quic_not_null_listener {
            get {
                return ResourceManager.GetString("net_quic_not_null_listener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be specified and contain at least one item to establish the connection..
        /// </summary>
        internal static string net_quic_not_null_not_empty_connection {
            get {
                return ResourceManager.GetString("net_quic_not_null_not_empty_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be specified and contain at least one item to start the listener..
        /// </summary>
        internal static string net_quic_not_null_not_empty_listener {
            get {
                return ResourceManager.GetString("net_quic_not_null_not_empty_listener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be specified to open the connection..
        /// </summary>
        internal static string net_quic_not_null_open_connection {
            get {
                return ResourceManager.GetString("net_quic_not_null_open_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted..
        /// </summary>
        internal static string net_quic_operationaborted {
            get {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A QUIC protocol error was encountered.
        /// </summary>
        internal static string net_quic_protocol_error {
            get {
                return ResourceManager.GetString("net_quic_protocol_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading has been aborted on the stream..
        /// </summary>
        internal static string net_quic_reading_aborted {
            get {
                return ResourceManager.GetString("net_quic_reading_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading is not allowed on stream..
        /// </summary>
        internal static string net_quic_reading_notallowed {
            get {
                return ResourceManager.GetString("net_quic_reading_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported by System.Net.Quic..
        /// </summary>
        internal static string net_quic_ssl_option {
            get {
                return ResourceManager.GetString("net_quic_ssl_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_streamaborted {
            get {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out waiting for a response from the peer..
        /// </summary>
        internal static string net_quic_timeout {
            get {
                return ResourceManager.GetString("net_quic_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout can only be set to &apos;System.Threading.Timeout.Infinite&apos; or a value &gt; 0..
        /// </summary>
        internal static string net_quic_timeout_use_gt_zero {
            get {
                return ResourceManager.GetString("net_quic_timeout_use_gt_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not use a TLS version required by Quic. TLS 1.3 may have been disabled in the registry..
        /// </summary>
        internal static string net_quic_tls_version_notsupported {
            get {
                return ResourceManager.GetString("net_quic_tls_version_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; in not supported remote endpoint type, expected IP or DNS endpoint.&quot;.
        /// </summary>
        internal static string net_quic_unsupported_endpoint_type {
            get {
                return ResourceManager.GetString("net_quic_unsupported_endpoint_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A version negotiation error was encountered..
        /// </summary>
        internal static string net_quic_ver_neg_error {
            get {
                return ResourceManager.GetString("net_quic_ver_neg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing has been aborted on the stream..
        /// </summary>
        internal static string net_quic_writing_aborted {
            get {
                return ResourceManager.GetString("net_quic_writing_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing is not allowed on stream..
        /// </summary>
        internal static string net_quic_writing_notallowed {
            get {
                return ResourceManager.GetString("net_quic_writing_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Net.Quic is not supported on this platform: {0}.
        /// </summary>
        internal static string SystemNetQuic_PlatformNotSupported {
            get {
                return ResourceManager.GetString("SystemNetQuic_PlatformNotSupported", resourceCulture);
            }
        }
    }
}
